{{- include "ffc-helm-library.container-secret" (list . "ffc-mpdp-frontend.container-secret") -}}
{{- define "ffc-mpdp-frontend.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  COOKIE_PASSWORD: {{ .Values.container.cookiePassword | quote }}
  {{- end }}
{{- end -}}
