services:
  ffc-mpdp-frontend:
    build:
      context: .
      target: production
    image: ffc-mpdp-frontend
    container_name: ffc-mpdp-frontend
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-mpdp-frontend-local
      APPINSIGHTS_CONNECTIONSTRING: ${APPINSIGHTS_CONNECTIONSTRING}
      GOOGLE_TAG_MANAGER_KEY: G-MYDRHM8BT1
      MPDP_BACKEND_ENDPOINT: "http://ffc-mpdp-backend:3000"
