services:
  ffc-mpdp-frontend:
    build:
      target: development
    image: ffc-mpdp-frontend-development
    container_name: ffc-mpdp-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json