version: '3.8'

services:
  ffc-ahwr-frontend:
    command: >
      sh -c "npm run test:watch:all"
    volumes:
      - ./app:/home/node/app
      - ./test:/home/node/test
      - ./jest.config.js:/home/node/jest.config.js
      - ./webpack.config.js:/home/node/webpack.config.js

volumes:
  dist:
  layouts:
