services:
  ffc-mpdp-frontend:
    build:
      target: development
    environment:
      NODE_ENV: test
    image: ffc-mpdp-frontend-development
    container_name: ffc-mpdp-frontend-test
    command: npm run test
    volumes:
      - ./test-output:/home/node/test-output
