# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-mpdp-frontend:
    build:
      target: development
    depends_on:
      - redis
    image: ffc-mpdp-frontend-development
    container_name: ffc-mpdp-frontend-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json

  redis:
    image: redis:4.0.14
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data:
