version: '3.8'

services:
  ffc-mpdp-frontend:
    build:
      context: .
      target: production
    image: ffc-mpdp-frontend
    container_name: ffc-mpdp-frontend
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-mpdp-frontend-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      MPDP_BACKEND_ENDPOINT: "http://ffc-mpdp-backend:3000"
      