services:
  ffc-mpdp-frontend:
    build:
      context: .
      target: production
    image: ffc-mpdp-frontend
    container_name: ffc-mpdp-frontend
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-mpdp-frontend-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      SERVICE_URI: http://localhost:3000
      