environment: development
name: ffc-mpdp-frontend
namespace: ffc-mpdp
workstream: ffc-mpdp
image: ffc-mpdp-frontend

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-mpdp-frontend-config-map

containerSecret:
  name: ffc-mpdp-frontend-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
